import { Vector2 } from "@/utils/Space";
import { IDot } from "./dots";

export const referenceDots: IDot[] = [
  {
    id: -1,
    type: "dot",
    position: new Vector2(0, 0),
    rotation: 0,
    color: "#FF0000",
    fixed: true,
    size: new Vector2(1, 1),
  },
  {
    id: -2,
    type: "corner",
    position: new Vector2(0, 1),
    rotation: 0,
    color: "#FF0000",
    fixed: true,
    size: new Vector2(1, 1),
  },
  {
    id: -3,
    type: "u",
    position: new Vector2(0, 2),
    rotation: 0,
    color: "#FF0000",
    fixed: true,
    size: new Vector2(1, 1),
  },
  {
    id: -4,
    type: "circle",
    position: new Vector2(0, 3),
    rotation: 0,
    color: "#FF0000",
    fixed: true,
    size: new Vector2(1, 1),
  },
  {
    id: -5,
    type: "curve",
    position: new Vector2(0, 4),
    rotation: 0,
    color: "#FF0000",
    fixed: true,
    size: new Vector2(2, 2),
  },
  {
    id: -6,
    type: "big-curve",
    position: new Vector2(0, 6),
    rotation: 0,
    color: "#FF0000",
    fixed: true,
    size: new Vector2(3, 3),
  },
  {
    id: -7,
    type: "dot2x1",
    position: new Vector2(1, 0),
    rotation: 0,
    color: "#FF0000",
    fixed: true,
    size: new Vector2(1, 2),
  },
  {
    id: -8,
    type: "dot3x1",
    position: new Vector2(2, 0),
    rotation: 0,
    color: "#FF0000",
    fixed: true,
    size: new Vector2(1, 3),
  },
  {
    id: -9,
    type: "dot4x1",
    position: new Vector2(3, 0),
    rotation: 0,
    color: "#FF0000",
    fixed: true,
    size: new Vector2(1, 4),
  },
];
